# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: The Reproducible Research Handbook
author: The Reproducible Research Group
logo: ../images/rr-logo-cropped.png
only_build_toc_files: true


# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: rr-handbook.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/Dartmouth-Libraries/reproducible-research  # Online location of your book
  path_to_book: rr-handbook
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true


launch_buttons:
  notebook_interface: "jupyterlab"  # or "classic"
  colab_url: "https://colab.research.google.com"
  jupyterhub_url: "https://jhub.dartmouth.edu"